### PR TITLE
#15: update all (closes #15)

### LINKED ISSUE #15: update all

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #15

### CODE REVIEW

**Comment by gabro** [comment]
You can use es6 for the webpack config, if you have the babel loader and call the file webpack.config.babel.js.

So you don't need object-assign either

**Comment by FrancescoCioria** [comment]
nice!
where can I find the code of the `web-seed` you've been working on these days? I'd like to set up `babel@6` too

**Comment by gabro** [comment]
buildo/revenge-webseed

gabriele
~ buildo

**Comment by FrancescoCioria** [comment]
@giogonzo I did this mostly cause I want to move `FlexView` to its own repo within the next month (I already blocked the name `react-flexview` :) )

**Comment by giogonzo** [comment]
> (I already blocked the names react-flexview and flexview on npm :stuck_out_tongue_closed_eyes: )

nice!

about the changes, they look good, although at this point we should rename the repo in `buildo-component-seed` or `react-component-seed` :P

the original goal of `web-lib-seed` was to share and reuse ignores, prepublish config, and not much more (and in fact it has been used for react-unrelated projects like sass-variables-loader, avenger, eslint-plugin-no-copy-paste-default-export, ...)
this now requires webpack, sass, and has react-specific dependencies included so..

**Pull request merged**
